### ISSUE TITLE
Error "The Instagram feed did not return JSON data"

### ISSUE THREAD

**Issue by hejchristiandev** [philhawksworth/netlify-plugin-add-instagram#6]
Hello, just wanted to report this issue I've been having recently - every build has been resulting in the plugin failing since updating to 0.2.5

> 11:56:32 AM:   Error location
> 11:56:32 AM:   In "onPreBuild" event in "netlify-plugin-add-instagram" from netlify.toml and package.json
> 11:56:32 AM:       at onPreBuild (/node_modules/netlify-plugin-add-instagram/index.js:40:21)

While the plugin isn't working for me recently, I did also want to thank you for introducing a more graceful method of failing the plugin itself instead of the entire build, So far I am able to keep an older 'copy' of the instagram feed on the website by using the older JSON from when it did manage to build last week :)

**Comment by smarteamom** [comment]
I'm seeing the same issue. 

```
FetchError: invalid json response body at https://www.instagram.com/accounts/login/?next=/myIGacct/%3F__a%3D1 reason: Unexpected token < in JSON at position 0

In "onPreBuild" event in "netlify-plugin-add-instagram" from netlify.toml and package.json at /opt/build/repo/node_modules/node-fetch/lib/index.js:272:32 at processTicksAndRejections (internal/process/task_queues.js:93:5) at async onPreBuild (/opt/build/repo/node_modules/netlify-plugin-add-instagram/index.js:25:20) at async Object.run (/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/plugins/child/run.js:18:3) at async handleEvent (/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/plugins/child/main.js:38:38) at async process.<anonymous> (/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/plugins/ipc.js:97:9)

Error properties: { type: 'invalid-json' }
```
